import Head from 'next/head';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import {
  faMagnifyingGlass,
  faCheck,
  faBookmark,
} from '@fortawesome/pro-regular-svg-icons';

import { IMovie } from '@/types/types';

import logo from '../public/logo.png';
import Image from 'next/image';

import Card from '@/components/Card';

import Navbar from '@/components/layout/Navbar';
import Footer from '@/components/layout/Footer';
import { Inter } from '@next/font/google';
import { getPopularMovies } from '@/movieService';

const inter = Inter({ subsets: ['latin'] });

export default function Movies({ movies }: { movies: IMovie[] }) {
  return (
    <>
      <Head>
        <title>Watchflix | Popular</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='min-h-screen flex flex-col grow bg-gradient-to-t from-slate-800 to-slate-900 '>
        <Navbar />
        <main className={'flex flex-col grow '}>
          <div
            className='text-left h-[50rem] p-6 bg-opacity-90 bg-cover bg-no-repeat bg-top mb-10 flex flex-col justify-end'
            style={{
              backgroundImage: `linear-gradient(to bottom, rgba(0, 0, 0, 0.5), rgba(0, 0, 0, .9)), url(https://image.tmdb.org/t/p/original${movies[0].backdrop_path})`,
            }}
          >
            {/* <img
                className='rounded-lg shadow-2xl md:mr-4 w-48 md:w-60 lg:w-80 mb-2'
                src={`https://image.tmdb.org/t/p/w400${movies[0].backdrop_path}`}
                alt='movie poster'
              /> */}
            <div className=' container mx-auto'>
              <div className='mb-5'>
                {' '}
                <h1 className='text-5xl font-bold mb-5'>{movies[0].title}</h1>
                <p className='text-md font-light mb-10'>{movies[0].overview}</p>
              </div>
              <h2 className='pl-2 pb-2 font-bold text-white text-xl md:text-2x'>
                Popular Now
              </h2>
              <div className='flex overflow-scroll-y w-full container mx-auto'>
                {movies
                  ? movies.map((movie) => (
                      <Card
                        key={movie.id}
                        id={movie.id}
                        title={movie.title}
                        poster={movie.poster_path}
                      />
                    ))
                  : ''}
              </div>
            </div>
          </div>
        </main>
        <Footer />
      </div>
    </>
  );
}

export async function getStaticProps() {
  const response = await getPopularMovies();
  console.log(response);
  const movies: IMovie[] = response.data.results;

  return {
    props: {
      movies,
    },
  };
}
