import Head from 'next/head';

import { IMovie } from '@/types/types';
import Navbar from '@/components/layout/Navbar';
import Footer from '@/components/layout/Footer';
import { Inter } from '@next/font/google';
import {
  getPopularMovies,
  getTopRatedMovies,
  getMoviesByYear,
} from '@/movieService';
import Carousel from '@/components/Carousel';
import LargeCarousel from '@/components/LargeCarousel';
const inter = Inter({ subsets: ['latin'] });

interface MoviesByYear {
  title: string;
  movies: IMovie[];
}

export default function Movies({
  topRatedMovies,
  popularMovies,
  moviesByYear,
}: {
  topRatedMovies: IMovie[];
  popularMovies: IMovie[];
  moviesByYear: MoviesByYear[];
}) {
  return (
    <>
      <Head>
        <title>Watchflix | Popular</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='flex min-h-screen grow flex-col bg-gradient-to-t from-slate-800 to-slate-900 '>
        <Navbar />
        <main className={'flex grow flex-col '}>
          <LargeCarousel movies={popularMovies} />

          <Carousel title={'Popular Now'} movies={popularMovies} />
          <Carousel
            title={'Highest Rated Movies of All Time'}
            movies={topRatedMovies}
          />

          {moviesByYear.map((year) => (
            <Carousel
              key={year.title}
              title={year.title}
              movies={year.movies}
            />
          ))}
        </main>
        <Footer />
      </div>
    </>
  );
}

export async function getStaticProps() {
  const popularMovies = await getPopularMovies();
  const topRatedMovies = await getTopRatedMovies();
  const randomYear = Math.floor(Math.random() * 52) + 1970;

  const moviesByYearOne = await getMoviesByYear(randomYear.toString());
  const moviesByYearTwo = await getMoviesByYear((randomYear + 1).toString());
  const moviesByYearThree = await getMoviesByYear((randomYear + 2).toString());

  const moviesByYear = [
    {
      title: `Best of ${randomYear}`,
      movies: moviesByYearOne,
    },
    {
      title: `Best of ${randomYear - 5}`,
      movies: moviesByYearTwo,
    },
    {
      title: `Best of ${randomYear + 5}`,
      movies: moviesByYearThree,
    },
  ];

  return {
    props: {
      popularMovies,
      topRatedMovies,
      moviesByYear,
    },
  };
}
