import Head from 'next/head';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import {
  faMagnifyingGlass,
  faCheck,
  faBookmark,
} from '@fortawesome/pro-regular-svg-icons';

import Navbar from '@/components/layout/Navbar';
import Footer from '@/components/layout/Footer';
import { Inter } from '@next/font/google';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Watchflix</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='min-h-screen flex flex-col grow bg-gradient-to-t from-blue-900 to-slate-900 '>
        <Navbar />
        <main
          className={'flex flex-col grow'}
          style={{
            backgroundImage: `linear-gradient( to bottom, rgba(0, 0, 0, 0.8), rgba(0, 0, 0, 0.7)), url('/background.webp')`,
          }}
        >
          <div className='text-center mx-auto px-20 my-28 flex-grow '>
            <div className='mb-24'>
              <h1 className='mb-10 h-100 mx-auto text-6xl md:text-8xl font-extrabold text-white  '>
                <div className=''>Browse less.</div>
                <div className=''>Watch more.</div>
              </h1>
              <p className='text-lg md:text-2xl text-slate-300 mb-10 block w-96 md:w-2/3 mx-auto'>
                Watchflix is a tool designed to simplify your movie search, so
                you can spend less time endlessly scrolling on movie night.
              </p>
              <button className='bg-blue-600 px-5 py-3 rounded-md font-semibold text-lg'>
                Get started
              </button>
            </div>

            <div className='flex flex-col md:flex-row  justify-around'>
              <div className='flex text-left p-3 w-full md:w-1/3'>
                <div className='p-7 w-5 h-5 bg-blue-500 rounded-md flex justify-center items-center'>
                  <FontAwesomeIcon
                    icon={faMagnifyingGlass}
                    className='text-lg md:text-xl'
                  />
                </div>
                <div className='ml-5'>
                  <p className=' text-xl font-medium leading-6'>
                    Search Movies
                  </p>
                  <p className='mt-2 text-base text-gray-400'>
                    Search through thousands of movies powered by The Movie
                    Database API
                  </p>
                </div>
              </div>

              <div className='flex text-left p-3 w-full md:w-1/3'>
                <div className='p-7 w-5 h-5 bg-blue-500 rounded-md flex justify-center items-center'>
                  <FontAwesomeIcon
                    icon={faCheck}
                    className='text-lg md:text-xl'
                  />
                </div>
                <div className='ml-5'>
                  <p className=' text-xl font-medium leading-6'>Track Movies</p>
                  <p className='mt-2 text-base text-gray-400'>
                    Keep track and rate all the movies you've seen
                  </p>
                </div>
              </div>

              <div className='flex text-left p-3 w-full md:w-1/3'>
                <div className='p-7 w-5 h-5 bg-blue-500 rounded-md flex justify-center items-center'>
                  <FontAwesomeIcon
                    icon={faBookmark}
                    className='text-lg md:text-xl'
                  />
                </div>
                <div className='ml-5'>
                  <p className=' text-xl font-medium leading-6'>Save Movies</p>
                  <p className='mt-2 text-base text-gray-400'>
                    Create a personal watchlist so your know what to watch up
                    next
                  </p>
                </div>
              </div>
            </div>
          </div>
        </main>
        <Footer />
      </div>
    </>
  );
}
