import Head from 'next/head';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import {
  faMagnifyingGlass,
  faCheck,
  faBookmark,
} from '@fortawesome/pro-regular-svg-icons';

import logo from '../public/logo.png';
import Image from 'next/image';
import Link from 'next/link';
import avengersPoster from '../public/landing_posters/avengers_poster.jpg';
import djangoPoster from '../public/landing_posters/django_poster.jpg';
import goodfellasPoster from '../public/landing_posters/goodfellas_poster.jpg';
import lotrPoster from '../public/landing_posters/lotr_poster.jpg';
import theDarkKnightPoster from '../public/landing_posters/the_dark_knight_poster.jpg';

import Footer from '@/components/layout/Footer';
import { Inter } from '@next/font/google';
import { getPopularMovies } from '@/movieService';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  const test = async () => {
    const res = await getPopularMovies();
    console.log(res);
  };

  test();
  return (
    <>
      <Head>
        <title>Watchflix</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='flex min-h-screen grow flex-col bg-gradient-to-t from-blue-900 to-slate-900 '>
        <main
          className={'flex grow flex-col '}
          style={{
            backgroundImage: `linear-gradient( to bottom, rgba(0, 0, 0, 0.8), rgba(0, 0, 0, 0.7)), url('/background.webp')`,
          }}
        >
          <div className='container mx-auto p-4'>
            <Image src={logo} alt='' className='w-32' />
          </div>
          <div className='my-8 flex-grow text-center md:my-12'>
            <div className='mb-24'>
              <h1 className='h-100 mx-auto mb-5 text-6xl font-extrabold text-white md:mb-8 md:text-7xl lg:text-8xl  '>
                <div>Browse less.</div>
                <div>Watch more.</div>
              </h1>

              <div
                className={
                  'mb-10 flex w-full justify-center gap-2 md:mb-12 md:gap-3 lg:gap-4'
                }
              >
                <Image
                  className={'w-20 rounded md:w-28 lg:w-36'}
                  src={avengersPoster}
                  alt='Movie poster for Avengers'
                />
                <Image
                  className={'w-20 translate-y-3 rounded md:w-28 lg:w-36'}
                  src={djangoPoster}
                  alt='Movie poster for Django Unchained'
                />
                <Image
                  className={'w-20 translate-y-6 rounded md:w-28 lg:w-36'}
                  src={goodfellasPoster}
                  alt='Movie poster for Goodfellas'
                />
                <Image
                  className={'w-20 translate-y-3 rounded md:w-28 lg:w-36'}
                  src={lotrPoster}
                  alt='Movie poster for Lord of the Rings: Return of the King'
                />
                <Image
                  className={'w-20 rounded md:w-28 lg:w-36'}
                  src={theDarkKnightPoster}
                  alt='Movie poster for '
                />
              </div>

              <p className='mx-auto mb-10 block w-96 text-lg text-slate-300 md:w-2/3 md:text-2xl'>
                Watchflix is a tool designed to simplify your movie search, so
                you can spend less time endlessly scrolling on movie night.
              </p>
              <Link href='/movies'>
                <button className='rounded-md bg-blue-600 px-5 py-3 text-lg font-semibold'>
                  Get started
                </button>
              </Link>
            </div>

            <div className='flex flex-col justify-around  md:flex-row'>
              <div className='flex w-full p-3 text-left md:w-1/3'>
                <div className='flex h-5 w-5 items-center justify-center rounded-md bg-blue-500 p-7'>
                  <FontAwesomeIcon
                    icon={faMagnifyingGlass}
                    className='text-lg md:text-xl'
                  />
                </div>
                <div className='ml-5'>
                  <p className=' text-xl font-medium leading-6'>
                    Search Movies
                  </p>
                  <p className='mt-2 text-base text-gray-400'>
                    Search through thousands of movies powered by The Movie
                    Database API
                  </p>
                </div>
              </div>

              <div className='flex w-full p-3 text-left md:w-1/3'>
                <div className='flex h-5 w-5 items-center justify-center rounded-md bg-blue-500 p-7'>
                  <FontAwesomeIcon
                    icon={faCheck}
                    className='text-lg md:text-xl'
                  />
                </div>
                <div className='ml-5'>
                  <p className=' text-xl font-medium leading-6'>Track Movies</p>
                  <p className='mt-2 text-base text-gray-400'>
                    Keep track and rate all the movies you see
                  </p>
                </div>
              </div>

              <div className='flex w-full p-3 text-left md:w-1/3'>
                <div className='flex h-5 w-5 items-center justify-center rounded-md bg-blue-500 p-7'>
                  <FontAwesomeIcon
                    icon={faBookmark}
                    className='text-lg md:text-xl'
                  />
                </div>
                <div className='ml-5'>
                  <p className=' text-xl font-medium leading-6'>Save Movies</p>
                  <p className='mt-2 text-base text-gray-400'>
                    Create a personal watchlist so your know what to watch up
                    next
                  </p>
                </div>
              </div>
            </div>
          </div>
        </main>
        <Footer />
      </div>
    </>
  );
}
